version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: unless-stopped

    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      # Already set in Dockerfile, but can override here if needed
      # CHOKIDAR_USEPOLLING: "true"
      # WATCHPACK_POLLING: "true"

    ports:
      - "3000:3000"

    volumes:

      # - .:/app

      # Use :delegated on Mac for better performance
      - .:/app:delegated

      - node_modules:/app/node_modules

      - next_cache:/app/.next

      - bun_cache:/root/.bun

    command: bun run dev

    networks:
      - default_network

networks:
  default_network:


volumes:
  node_modules:
  next_cache:
  bun_cache:
